# This is a workflow sends notifications to slack if the getro board has new jobs or has deleted jobs

name: Getro Scheduled Sync

# Controls when the workflow will run
on:
  # Triggers the workflow on a schedule
  schedule:
  - cron: '0 */6 * * 1-5'
  # Manual run for testing
  # workflow_dispatch:

# The workflow will have two jobs running in parallel, one for the farming table, the other for the hunting table
jobs:
  # First job is for the farming table
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repo under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v3
      - name: create env file
        run: |
            touch .env
            echo GETRO_API_EMAIL=${{ secrets.GETRO_API_EMAIL }} >> .env
            echo GETRO_API_TOKEN=${{ secrets.GETRO_API_TOKEN }} >> .env
            echo GETRO_API_FARMING_NETWORK_ID=${{ secrets.GETRO_API_FARMING_NETWORK_ID }} >> .env
            echo GETRO_API_HUNTING_NETWORK_ID=${{ secrets.GETRO_API_HUNTING_NETWORK_ID }} >> .env
      
      # first download the last artefact of getro job ids
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: getro.yml
          # Optional, the status or conclusion of a completed workflow to search for
          workflow_conclusion: success
          name: getro
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: ./
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts:  true
          # Optional, choose how to exit the action if no artifact is found
          # can be one of:
          #  "fail", "warn", "ignore"
          # default fail
          if_no_artifact_found: warn        
          
      # run the index.js code
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: echo Done installing node modules
      - run: node index.js
      - run: echo Done running script, now uploading artefact

      # upload the updated artefact of getro job ids
      - name: Upload the getro artefact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: getro
          path: ./farmingGetro.txt
          # The desired behavior if no files are found using the provided path. warn,error,ignore
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 1
      - name: Upload the getro artefact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: getro
          path: ./huntingGetro.txt
          # The desired behavior if no files are found using the provided path. warn,error,ignore
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Upload of artefact completed
          echo Actions done
